version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: develop
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: electron
    versions:
    - 11.2.1
