version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "10:00"
    open-pull-requests-limit: 10
    target-branch: main
    versioning-strategy: increase-if-necessary
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
