name: Build/release for Snap

on: push

defaults:
  run:
    shell: bash

jobs:
  snap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, armv7l]
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
      GH_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build
        run: yarn --link-duplicates --pure-lockfile

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Build for test only
        if: github.ref != 'refs/heads/main'
        run: yarn dist:linux:snap:${{ matrix.arch }} --publish never

      - name: Release
        if: github.ref == 'refs/heads/main'
        run: yarn dist:linux:snap:${{ matrix.arch }} --publish always
